import type { Metadata } from "next";
import "./globals.css";
import { AppSidebar } from "@/components/sidebar/app-sidebar";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { ThemeProvider } from "@/components/themes/theme-provider"
import { ThemeToggle } from "@/components/themes/theme-toggle";
import { Toaster } from 'sonner'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className="flex h-screen text-black dark:text-white antialiased flex-shrink-0"
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <Toaster richColors />
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset className="flex-1 min-w-0 flex-col">
              <header className="flex h-14 shrink-0 items-center justify-between transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12">
                <div className="flex items-center gap-2 px-4">
                  <SidebarTrigger className="-ml-1 text-black dark:text-white" />
                </div>
                <div className="flex items-center gap-2 px-4">
                  <ThemeToggle className="-mr-1" />
                </div>
              </header>
              {children}
            </SidebarInset>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
